include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
   - macros
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: ignore
  exclude:
    - "*.g.dart"
    - "**/*.g.dart"

linter:
  rules:
    avoid_redundant_argument_values: true
    always_use_package_imports: true
    flutter_style_todos: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_single_quotes: true
    sort_constructors_first: true
    require_trailing_commas: true
    unawaited_futures: true