name: app
description: "Plan die shit met Poker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  go_router: ^14.6.3
  logger: ^2.5.0
  intl: 
  get_it: ^8.0.3
  hooks_riverpod: ^2.6.1
  dartz: ^0.10.1
  shared_preferences: ^2.3.5
  vector_graphics: ^1.1.15
  forui: ^0.7.0
  forui_assets: ^0.7.0
  gap: ^3.0.1
  forui_hooks: ^0.7.0+1
  pocketbase: ^0.21.0
  uuid: ^4.5.1
  slugify: ^2.0.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: 
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  custom_lint: ^0.7.1

flutter:
  uses-material-design: true
  generate: true